export const recipes = [
    {
      name: "No-Bake Cheesecake",
      category: ["Cake", "No-Bake", "Vegetarian"],
      ingredients: [
        "Condensed milk",
        "Cream cheese",
        "Lemon juice",
        "Pie crust",
        "Cherry jam",
      ],
      steps: [
        "Beat cream cheese.",
        "Add condensed milk and blend.",
        "Add Lemon Juice and blend.",
        "Add the mix to the pie crust.",
        "Spread the Cherry jam.",
        "Place in refrigerator for 3h.",
      ],
    },
    {
      name: "Roasted Brussels Sprouts",
      category: ["Vegan", "Gluten-Free"],
      ingredients: [
        "Brussels Sprouts",
        "Lemon juice",
        "Sesame seeds",
        "Pepper",
        "Salt",
        "Olive oil",
      ],
      steps: [
        "Preheat the oven.",
        "Mix the ingredients in a bowl.",
        "Spread the mix on baking sheet.",
        "Bake for 30 minutes.",
      ],
    },
    {
      name: "Mac & Cheese",
      category: ["Vegetarian"],
      ingredients: [
        "Macaroni",
        "Butter",
        "Flour",
        "Salt",
        "Pepper",
        "Milk",
        "Shredded Cheddar cheese",
      ],
      steps: [
        "Cook Macaroni for 8 minutes.",
        "Melt butter in a saucepan.",
        "Add flour, salt, pepper and mix.",
        "Add Milk and mix.",
        "Cook until mix is smooth.",
        "Add cheddar cheese.",
        "Add the macaroni.",
      ],
    },
    {
      name: "Tamagoyaki Japanese Omelette",
      category: ["Vegetarian", "Japanese"],
      ingredients: ["Eggs", "Soy sauce", "Sugar", "Salt", "Olive oil"],
      steps: [
        "Beat the eggs.",
        "Add soya sauce, sugar and salt.",
        "Add oil to a sauce pan.",
        "Bring to medium heat.",
        "Add some mix to the sauce pan.",
        "Let it cook for 1 minute.",
        "Remove pan from fire.",
      ],
    },
  ];
  